// HTTP Status Codes, UI Timeouts, Validation Limits, etc.
export const CONSTANTS = {
    MAX_RETRIES: 3,
    INITIAL_RETRY_DELAY: 1000,
    MAX_RETRY_DELAY: 5000,

    CACHE_DURATION: 15 * 60 * 1000,
    CACHE_KEY_PREFIX: "ksss_cache_",

    MATCHES_PER_PAGE: 20,
    MAX_HISTORY_ENTRIES: 50,

    MAX_HOME_MATCHES: 6,

    SUCCESS_MESSAGE_DURATION: 4000,
    ERROR_MESSAGE_DURATION: 0,
    RELOAD_DELAY_AFTER_SAVE: 1500,
    VALIDATION_ERROR_DISPLAY: 2000,

    MIN_SCORE: 0,
    MAX_SCORE: 100,

    MATCH_TYPE_NORMAL: "normal",
    MATCH_TYPE_BEST_LOSER: "best_loser",

    ROUND_STATUS_ACTIVE: "active",
    ROUND_STATUS_LOCKED: "locked",

    DEFAULT_LOCATION: "Maths Lab",
    DEFAULT_TIME: "TBD",
    DEFAULT_DATE: "Pending",

    HTTP_UNAUTHORIZED: 401,
    HTTP_FORBIDDEN: 403,
    HTTP_NOT_FOUND: 404,
    HTTP_CONFLICT: 409,
    HTTP_UNPROCESSABLE: 422,
    HTTP_RATE_LIMIT: 429,
    HTTP_SERVER_ERROR: 500
};